# Generated by Django 5.2 on 2025-05-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_candidatecv_file_alter_jobpost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecv',
            name='file',
            field=models.FileField(upload_to='candidate_cvs/'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='file',
            field=models.FileField(upload_to='job_descriptions/'),
        ),
    ]
